export const POPULAR_MOVIES_FETCH_SUCCEEDED = "POPULAR_MOVIES_FETCH_SUCCEEDED";
export const POPULAR_MOVIES_FETCH_REQUEST = "POPULAR_MOVIES_FETCH_REQUEST";
export const POPULAR_MOVIES_FETCH_FAILED = "POPULAR_MOVIES_FETCH_FAILED";

export const TOPRATED_MOVIES_FETCH_SUCCEEDED = "TOPRATED_MOVIES_FETCH_SUCCEEDED";
export const TOPRATED_MOVIES_FETCH_REQUEST = "TOPRATED_MOVIES_FETCH_REQUEST";
export const TOPRATED_MOVIES_FETCH_FAILED = "TOPRATED_MOVIES_FETCH_FAILED";

export const LATEST_TRAILERS_FETCH_SUCCEEDED = "LATEST_TRAILERS_FETCH_SUCCEEDED";
export const LATEST_TRAILERS_FETCH_REQUEST = "LATEST_TRAILERS_FETCH_REQUEST";
export const LATEST_TRAILERS_FETCH_FAILED = "LATEST_TRAILERS_FETCH_FAILED";

export const REVIEWS_FETCH_SUCCEEDED = "REVIEWS_FETCH_SUCCEEDED";
export const REVIEWS_FETCH_REQUEST = "REVIEWS_FETCH_REQUEST";
export const REVIEWS_FETCH_FAILED = "REVIEWS_FETCH_FAILED";
